//#region Imports

import PERSON_FIELDS from 'utils/constants/fields/person';

//#endregion

const personFormat = (data, image) => ({
    [PERSON_FIELDS.WORK]: {
        [PERSON_FIELDS.POSITION]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.WORK][PERSON_FIELDS.POSITION],
        [PERSON_FIELDS.COUNTRY_CODE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.WORK][PERSON_FIELDS.COUNTRY_CODE]
    },
    [PERSON_FIELDS.PERSONAL]: {
        [PERSON_FIELDS.IMAGE]: image,
        [PERSON_FIELDS.AGE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.AGE],
        [PERSON_FIELDS.NAME]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.NAME],
        [PERSON_FIELDS.GENDER]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.GENDER],
        [PERSON_FIELDS.NATIONAL_CODE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.NATIONAL_CODE]
    }
});

export default personFormat;
