//#region Imports

import PERSON_FIELDS from 'utils/constants/fields/person';

//#endregion

const personFormat = (data, image) => ({
    [PERSON_FIELDS.WORK]: {
        [PERSON_FIELDS.SALARY]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.WORK][PERSON_FIELDS.SALARY],
        [PERSON_FIELDS.POSITION]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.WORK][PERSON_FIELDS.POSITION],
        [PERSON_FIELDS.COUNTRY_CODE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.WORK][PERSON_FIELDS.COUNTRY_CODE]
    },
    [PERSON_FIELDS.PERSONAL]: {
        [PERSON_FIELDS.IMAGE]: image,
        [PERSON_FIELDS.AGE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.AGE],
        [PERSON_FIELDS.NAME]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.NAME],
        [PERSON_FIELDS.GENDER]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.GENDER],
        [PERSON_FIELDS.WEIGHT]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.WEIGHT],
        [PERSON_FIELDS.HEIGHT]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.HEIGHT],
        [PERSON_FIELDS.CELLPHONE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.CELLPHONE],
        [PERSON_FIELDS.NATIONAL_CODE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.NATIONAL_CODE]
    },
    [PERSON_FIELDS.LOCAL]: {
        [PERSON_FIELDS.CITY]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.CITY],
        [PERSON_FIELDS.COUNTRY]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.COUNTRY],
        [PERSON_FIELDS.BORN_PLACE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.PERSONAL][PERSON_FIELDS.BORN_PLACE]
    },
    [PERSON_FIELDS.EDUCATION]: {
        [PERSON_FIELDS.UNIVERSITY]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.EDUCATION][PERSON_FIELDS.UNIVERSITY],
        [PERSON_FIELDS.CERTIFICATE]: data[PERSON_FIELDS.PERSON][PERSON_FIELDS.EDUCATION][PERSON_FIELDS.CERTIFICATE]
    }
});

export default personFormat;
